openai_api_key: "YOUR_OPENAI_API_KEY"
model4_name: "gpt-4-1106-preview"
model3_name: "gpt-3.5-turbo-1106"
numeric_attribute_template: |
  You are a data analyst. You are cleaning the data and processing the attributes in the data that are not numeric. The columns to be processed include: {attributes}. The first 20 items of these data are as follows:
  {data_frame_head}
  Please help me decide whether each attribute should be processed as integer mapping or one-hot encoding based on content and semantics. Integer mapping is represented by 1, and one-hot encoding is represented by 2. Only the data is returned in json format without any other explanation or content. Sample response: {{"color":2,"size":1,"country":2,"brand":2,"gender":1}}
null_attribute_template: |
  You are a data analyst. You are preprocessing the attributes in the data that contain null values. The columns to be processed include: {attributes}. The types of these attributes are:
  {types_info}
  Statistics for these properties in csv format:
  {description_info}
  Please help me decide how to supplement null values for each attribute based on content, statistics and semantics. The mean filling is represented by 1, the median filling is represented by 2, the mode filling is represented by 3, the introduction of a new category to represent the unknown is represented by 4, and the interpolation filling is represented by 5. Only the data is returned in json format without any other explanation or content. Sample response: {{"grade":2,"annual_income":2,"temperature":1,"fault_type":3,"country":4,"weight":1,"stock price":5}}
decide_model_template: |
  You are a data analyst. The shape of my data frame is {shape_info}. The head(5) of the data frame is:
  {head_info}
  The nunique() of the data frame is:
  {nunique_info}
  The description of the data frame is:
  {description_info}
  The data has been cleaned and preprocessed, nulls filled, and encoded ready to train the machine learning model. According to the data information provided, please help me decide which machine learning models should be used for classification prediction. Model options are: 1:LogisticRegression, 2:SVC, 3:GaussianNB, 4:RandomForestClassifier, 5:AdaBoostClassifier, 6:XGBClassifier, 7:GradientBoostingClassifier. Please select three models to take into account different model performance indicators. Only the data is returned in json format without any other explanation or content. Sample response: {{"model1":1,"model2":4,"model3":6}}